# Generated by Django 3.1.4 on 2020-12-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusetudiant',
            name='statut',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
